gsettings set org.gnome.TextEditor auto-indent true
gsettings set org.gnome.TextEditor auto-save-delay 3
gsettings set org.gnome.TextEditor custom-font 'Monospace 11'
gsettings set org.gnome.TextEditor discover-settings false
gsettings set org.gnome.TextEditor enable-snippets false
gsettings set org.gnome.TextEditor highlight-current-line true
gsettings set org.gnome.TextEditor highlight-matching-brackets true
gsettings set org.gnome.TextEditor indent-style 'space'
gsettings set org.gnome.TextEditor indent-width -1
gsettings set org.gnome.TextEditor keybindings 'default'
gsettings set org.gnome.TextEditor last-save-directory 'file:///home/jur'
gsettings set org.gnome.TextEditor line-height 1.2
gsettings set org.gnome.TextEditor recolor-window true
gsettings set org.gnome.TextEditor restore-session false
gsettings set org.gnome.TextEditor right-margin-position 120
gsettings set org.gnome.TextEditor show-grid false
gsettings set org.gnome.TextEditor show-line-numbers true
gsettings set org.gnome.TextEditor show-map false
gsettings set org.gnome.TextEditor show-right-margin true
gsettings set org.gnome.TextEditor spellcheck true
gsettings set org.gnome.TextEditor style-scheme 'classic-dark'
gsettings set org.gnome.TextEditor style-variant 'dark'
gsettings set org.gnome.TextEditor tab-width 4
gsettings set org.gnome.TextEditor use-system-font true
gsettings set org.gnome.TextEditor wrap-text true
gsettings set org.gnome.TextEditor auto-indent true
gsettings set org.gnome.TextEditor auto-save-delay 3
gsettings set org.gnome.TextEditor custom-font 'Monospace 11'
gsettings set org.gnome.TextEditor discover-settings false
gsettings set org.gnome.TextEditor enable-snippets false
gsettings set org.gnome.TextEditor highlight-current-line true
gsettings set org.gnome.TextEditor highlight-matching-brackets true
gsettings set org.gnome.TextEditor indent-style 'space'
gsettings set org.gnome.TextEditor indent-width -1
gsettings set org.gnome.TextEditor keybindings 'default'
gsettings set org.gnome.TextEditor last-save-directory 'file:///home/jur'
gsettings set org.gnome.TextEditor line-height 1.2
gsettings set org.gnome.TextEditor recolor-window true
gsettings set org.gnome.TextEditor restore-session false
gsettings set org.gnome.TextEditor right-margin-position 120
gsettings set org.gnome.TextEditor show-grid false
gsettings set org.gnome.TextEditor show-line-numbers false
gsettings set org.gnome.TextEditor show-map false
gsettings set org.gnome.TextEditor show-right-margin true
gsettings set org.gnome.TextEditor spellcheck true
gsettings set org.gnome.TextEditor style-scheme 'classic-dark'
gsettings set org.gnome.TextEditor style-variant 'dark'
gsettings set org.gnome.TextEditor tab-width 4
gsettings set org.gnome.TextEditor use-system-font true
gsettings set org.gnome.TextEditor wrap-text true

